version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          - v2-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - "$HOME/.npm"
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run -s typecheck

      - run: npm run -s lint
